"""Generate ready-to-use deployment artifacts for the node.

One endpoint per artifact:
  GET /api/wiz/admin/deploy/dockerfile      → text/plain
  GET /api/wiz/admin/deploy/docker-compose  → text/yaml
  GET /api/wiz/admin/deploy/systemd.service → text/plain (Linux unit)
  GET /api/wiz/admin/deploy/launchd.plist   → application/xml (macOS)
  GET /api/wiz/admin/deploy/all.zip         → full bundle as ZIP

Each artifact is generated fresh from the current .env, so paths /
PORT / KEYS_DIR / DEVICE_NAME match the running configuration.
"""
from __future__ import annotations

import io
import logging
import os
import re
import time
import zipfile
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Request
from fastapi.responses import Response, StreamingResponse

from . import backup_api as _b

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/wiz/admin/deploy", tags=["deploy"])


def _env_file(request: Request) -> Path:
    p = getattr(request.app.state, "env_file", None)
    return Path(p) if p else Path(".env")


# ── Dockerfile ────────────────────────────────────────────────────────────

def _dockerfile(env: dict) -> str:
    port = env.get("PORT", "9000")
    return f"""# Vortex node — auto-generated by the wizard.
# Review before deploying; regenerate after config changes.
FROM python:3.13-slim

# System deps — cryptography backend, liboqs for PQ, image libs for stego
RUN apt-get update && apt-get install -y --no-install-recommends \\
        build-essential libssl-dev libffi-dev libjpeg-dev zlib1g-dev \\
        cmake ninja-build libgmp-dev pkg-config curl \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/vortex
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Optional: build the Rust hot-path extension for 10-40x speedups
# (comment out to fall back to pure-Python)
# COPY rust_utils rust_utils/
# RUN pip install --no-cache-dir maturin && \\
#     cd rust_utils && maturin develop --release && cd ..

COPY . .

ENV PORT={port} HOST=0.0.0.0
EXPOSE {port}

# Non-root user for runtime
RUN useradd -m -u 10000 vortex && chown -R vortex:vortex /opt/vortex
USER vortex

HEALTHCHECK --interval=30s --timeout=4s --start-period=20s --retries=3 \\
    CMD curl -fsS http://127.0.0.1:{port}/health || exit 1

CMD ["python", "run.py"]
"""


def _compose_file(env: dict) -> str:
    port = env.get("PORT", "9000")
    device = env.get("DEVICE_NAME", "vortex-node")
    safe_device = re.sub(r"[^a-z0-9_-]", "-", device.lower())[:32] or "vortex-node"
    return f"""# docker-compose.yml — full Vortex stack (node + optional Postgres).
# Generated {time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())}.
version: "3.8"

services:
  {safe_device}:
    build: .
    image: vortex-node:latest
    container_name: {safe_device}
    restart: unless-stopped
    ports:
      - "{port}:{port}"
    environment:
      HOST: "0.0.0.0"
      PORT: "{port}"
      NETWORK_MODE: "{env.get("NETWORK_MODE", "local")}"
      CONTROLLER_URL: "{env.get("CONTROLLER_URL", "")}"
      CONTROLLER_PUBKEY: "{env.get("CONTROLLER_PUBKEY", "")}"
      # DATABASE_URL set below when postgres service is enabled.
    volumes:
      - ./keys:/opt/vortex/keys:ro
      - vortex-data:/opt/vortex/data
    # Uncomment to enable managed Postgres:
    # depends_on: [postgres]
    # environment:
    #   DATABASE_URL: "postgresql://vortex:CHANGE_ME@postgres:5432/vortex"

  # Uncomment for managed Postgres:
  # postgres:
  #   image: postgres:17-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: vortex
  #     POSTGRES_PASSWORD: CHANGE_ME
  #     POSTGRES_DB: vortex
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

volumes:
  vortex-data:
  # postgres-data:
"""


# ── systemd service unit ──────────────────────────────────────────────────

def _systemd_unit(env: dict, workdir: Path) -> str:
    device = env.get("DEVICE_NAME", "vortex-node") or "vortex-node"
    user = env.get("DEPLOY_USER", "vortex")
    return f"""# /etc/systemd/system/vortex-{device}.service
# Install with:
#   sudo cp vortex-{device}.service /etc/systemd/system/
#   sudo systemctl daemon-reload
#   sudo systemctl enable --now vortex-{device}.service
# View logs with:
#   journalctl -fu vortex-{device}.service

[Unit]
Description=Vortex P2P messenger node ({device})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={user}
Group={user}
WorkingDirectory={workdir}
Environment="HOST={env.get("HOST", "0.0.0.0")}"
Environment="PORT={env.get("PORT", "9000")}"
Environment="NETWORK_MODE={env.get("NETWORK_MODE", "local")}"
Environment="PYTHONUNBUFFERED=1"
EnvironmentFile=-{workdir}/.env
ExecStart=/usr/bin/env python3 run.py
Restart=on-failure
RestartSec=5s
TimeoutStopSec=30s

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
DevicePolicy=closed
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
LockPersonality=true
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
MemoryDenyWriteExecute=false
ReadWritePaths={workdir}

# Resource limits
LimitNOFILE=65536
LimitNPROC=4096
MemoryHigh=4G
MemoryMax=6G
TasksMax=512

[Install]
WantedBy=multi-user.target
"""


# ── launchd plist (macOS) ─────────────────────────────────────────────────

def _launchd_plist(env: dict, workdir: Path) -> str:
    device = env.get("DEVICE_NAME", "vortex-node") or "vortex-node"
    safe = re.sub(r"[^A-Za-z0-9.-]", "-", device.lower())
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Install:
    cp com.vortex.{safe}.plist ~/Library/LaunchAgents/
    launchctl load -w ~/Library/LaunchAgents/com.vortex.{safe}.plist

  Logs: ~/Library/Logs/vortex-{safe}.out / .err
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.vortex.{safe}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>{workdir}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/env</string>
        <string>python3</string>
        <string>run.py</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOST</key><string>{env.get("HOST", "0.0.0.0")}</string>
        <key>PORT</key><string>{env.get("PORT", "9000")}</string>
        <key>NETWORK_MODE</key><string>{env.get("NETWORK_MODE", "local")}</string>
        <key>PYTHONUNBUFFERED</key><string>1</string>
    </dict>
    <key>StandardOutPath</key>
    <string>{os.path.expanduser("~")}/Library/Logs/vortex-{safe}.out</string>
    <key>StandardErrorPath</key>
    <string>{os.path.expanduser("~")}/Library/Logs/vortex-{safe}.err</string>
    <key>ProcessType</key>
    <string>Interactive</string>
    <key>LowPriorityIO</key>
    <false/>
</dict>
</plist>
"""


# ── Endpoints ─────────────────────────────────────────────────────────────

@router.get("/dockerfile")
async def get_dockerfile(request: Request) -> Response:
    env = _b._read_env(_env_file(request))
    return Response(content=_dockerfile(env), media_type="text/plain")


@router.get("/docker-compose")
async def get_compose(request: Request) -> Response:
    env = _b._read_env(_env_file(request))
    return Response(content=_compose_file(env), media_type="text/yaml")


@router.get("/systemd.service")
async def get_systemd(request: Request) -> Response:
    env_file = _env_file(request)
    env = _b._read_env(env_file)
    return Response(content=_systemd_unit(env, env_file.parent.resolve()),
                    media_type="text/plain")


@router.get("/launchd.plist")
async def get_launchd(request: Request) -> Response:
    env_file = _env_file(request)
    env = _b._read_env(env_file)
    return Response(content=_launchd_plist(env, env_file.parent.resolve()),
                    media_type="application/xml")


@router.get("/all.zip")
async def get_bundle(request: Request) -> StreamingResponse:
    env_file = _env_file(request)
    env = _b._read_env(env_file)
    workdir = env_file.parent.resolve()

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("Dockerfile", _dockerfile(env))
        zf.writestr("docker-compose.yml", _compose_file(env))
        zf.writestr("vortex-node.service", _systemd_unit(env, workdir))
        zf.writestr("com.vortex.node.plist", _launchd_plist(env, workdir))
        zf.writestr("README.md", _readme(env))
    buf.seek(0)
    filename = f"vortex-deploy-{time.strftime('%Y%m%d')}.zip"
    return StreamingResponse(
        buf, media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


def _readme(env: dict) -> str:
    return f"""# Vortex deploy bundle

Generated {time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())} for
device "{env.get("DEVICE_NAME", "vortex-node")}".

## Files

- **Dockerfile** + **docker-compose.yml** — containerised deploy.
- **vortex-node.service** — Linux systemd unit. Copy to
  `/etc/systemd/system/`, then `systemctl enable --now`.
- **com.vortex.node.plist** — macOS launchd agent. Copy to
  `~/Library/LaunchAgents/`, then `launchctl load -w`.

Each file has inline comments explaining install / verification steps.

## Notes

- Dockerfile builds pure Python by default. Uncomment the Rust block to
  enable 10–40× hot-path speedups (BMP, canonical JSON, sealed sender).
- systemd unit uses the current working directory. Regenerate after
  moving the install.
- launchd plist sends logs to `~/Library/Logs/vortex-*.{{out,err}}`.
"""
